---
title       : Waterloo Neighbourhood Browser
subtitle    : Interactive geo data visualizer
author      : Jeremy Shantz
job         : https://linkedin.com/in/jeremyshantz
logo        : logo.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn      # 
widgets     : [bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Read-And-Delete

*  
*
*

--- .class #id 

## Slide 3


```{r, echo=FALSE}

suppressPackageStartupMessages(library(googleVis))
suppressPackageStartupMessages(library(dplyr))

# Load our dataset
address <<- read.csv('../../app/AddressPoints.csv')

# Concatenate lat and long 
address$latlong <- paste(address$LATITUDE, address$LONGITUDE, sep=":")

# Clean for display
address <- select(address, -OBJECTID, -LATITUDE, -LONGITUDE)
row.names(address) <- NULL
names(address) <- c('Address', 'Street', 'Ward', 'District', 'Coordinates')
wards <- sort(unique(address$Ward[!is.na(address$Ward) & address$Ward > 0]))

```

```{r}

unique(as.character(address$District))



```

--- .class

## Slide 4


--- .class

## Slide 5

### Check it out: [https://jeremyshantz.shinyapps.io/waterloo/](https://jeremyshantz.shinyapps.io/waterloo/)

kerbam!
